<?php
/**
 * @file
 * Custom Slogan Module
 */

/**
 * Implements hook_help().
 */
function custom_slogan_help($path, $arg) {
  // This is moved on an experimental basis.
  module_load_include('inc', 'custom_slogan', 'custom_slogan.help');
  return _custom_slogan_help($path, $arg);
}

/**
 * Implements hook_menu().
 */
function snippets_menu() {
  $items['admin/config/content/custom_slogan'] = array(
    'title' => 'Custom Slogan',
    'description' => "Configure Custom Slogan module.",
    'route_name' => 'custom_slogan.settings',
  );

  return $items;
}

/**
 * Implements of hook_theme().
 */
function custom_slogan_theme() {
  return array(
    'custom_slogan_preprocess_html' => array(
      'arguments' => array('vars' => NULL),
    ),
  );
}

  /**
 * Implements hook_entity_load().
 */
  public function custom_slogan_entity_load($entities) {
    foreach ($nodes as $node) {

    }
  }

  /**
 * Implement hook_node_insert().
 */
  public function custom_slogan_node_insert(EntityInterface $node) {
    if (user_access('set custom slogan') && isset($node->custom_slogan) && drupal_strlen(trim($node->custom_slogan)) > 0) {
      db_insert('custom_slogan')
        ->fields(array(
        'type' => 'node',
        'id' => $node->nid,
        'custom_slogan' => $node->custom_slogan
      ))
        ->execute();
    }
  }

  /**
 * Implement hook_node_update().
 */
  public function custom_slogan_node_update(EntityInterface $node) {
    if (user_access('set custom slogan') && isset($node->custom_slogan)) {
      if (drupal_strlen(trim($node->page_title)) > 0) {
        db_merge('custom_slogan')
          ->key(array('type' => 'node', 'id' => $node->nid))
          ->fields(array('custom_slogan' => $node->custom_slogan))
          ->execute();
      }
      else {
        custom_slogan_node_delete(EntityInterface $node);
      }
    }
  }

  /**
 * Implement hook_node_delete().
 */
  public function custom_slogan_node_delete(EntityInterface $node) {
    db_delete('custom_slogan')
      ->condition('type', 'node')
      ->condition('id', $node->nid)
      ->execute();
  }

/**
 * Implement hook_taxonomy_term_insert().
 */
  public function custom_slogan_taxonomy_term_insert(Drupal taxonomy Term $term) {
    if (user_access('set custom slogan') && isset($term->custom_slogan) && drupal_strlen(trim($term->custom_slogan)) > 0) {
      db_insert('custom_slogan')
        ->fields(array(
        'type' => 'term',
        'id' => $term->tid,
        'custom_slogan' => $term->custom_slogan
      ))
        ->execute();
    }
  }


/**
 * Implement hook_taxonomy_term_update().
 */
  public function custom_slogan_taxonomy_term_update(Drupal taxonomy Term $term) {
    if (user_access('set custom slogan')) {
      if (isset($term->custom_slogan) && drupal_strlen(trim($term->custom_slogan)) > 0) {
        db_merge('custom_slogan')
          ->key(array('type' => 'term', 'id' => $term->tid))
          ->fields(array('custom_slogan' => $term->custom_slogan))
          ->execute();
      }
      else {
        custom_slogan_taxonomy_term_delete(Drupal taxonomy Term $term);
      }
    }
  }

  /**
 * Implement hook_taxonomy_term_delete().
 */
  public function custom_slogan_taxonomy_term_delete(Drupal taxonomy Term $term) {
    db_delete('custom_slogan')
      ->condition('type', 'term')
      ->condition('id', $term->tid)
      ->execute();
  }
}

/**
 * Implement hook_preprocess_html().
 */
function custom_slogan_preprocess_html(&$vars) {
  $slogan = custom_slogan_page_get_slogan();
  if(empty($slogan)) {
    $vars['site_slogan'] = $slogan;
  }
  else {
    $vars['site_slogan'] = variable_get('site_slogan', '');
  }
}
