<?php
/**
 * @file
 * Custom Slogan Module
 */

/**
 * Implements hook_help().
 */
function custom_slogan_help($path, $arg) {
  // This is moved on an experimental basis.
  module_load_include('inc', 'custom_slogan', 'custom_slogan.help');
  return _custom_slogan_help($path, $arg);
}

/**
 * Implements hook_menu().
 */
function snippets_menu() {
  $items['admin/config/content/custom_slogan'] = array(
    'title' => 'Custom Slogan',
    'description' => "Configure Custom Slogan module.",
    'route_name' => 'custom_slogan.settings',
  );

  return $items;
}
